# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

identity <- function(L, p, m) {
    .Call(`_clifford_identity`, L, p, m)
}

add <- function(L1, c1, L2, c2, m) {
    .Call(`_clifford_add`, L1, c1, L2, c2, m)
}

multiply <- function(L1, c1, L2, c2, m, sig) {
    .Call(`_clifford_multiply`, L1, c1, L2, c2, m, sig)
}

c_power <- function(L1, c1, L2, c2, m, p, sig) {
    .Call(`_clifford_c_power`, L1, c1, L2, c2, m, p, sig)
}

add <- function(L1, c1, L2, c2, m) {
    .Call(`_clifford_add`, L1, c1, L2, c2, m)
}

c_equality <- function(L1, c1, L2, c2, m) {
    .Call(`_clifford_c_equality`, L1, c1, L2, c2, m)
}

