# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      TINYTEX_INSTALLER: TinyTeX
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2

      - name: Install dependencies
        run: |
        remotes::install_deps(dependencies = TRUE)
        remotes::install_cran("rcmdcheck")
        tinytex::parse_install( text = "! LaTeX Error: File ae.sty' not found.") tinytex::parse_install( text = "! LaTeX Error: File footmisc.sty' not found.")
        tinytex::parse_install( text = "! LaTeX Error: File ctable.sty' not found.") tinytex::parse_install( text = "! LaTeX Error: File grfext.sty' not found.")
        shell: Rscript {0}
